evaluation:
  evaluate_after: -1
  every_eval: 1
  print_every: 100
logging:
  print_level: DEBUG
  write_level: INFO
misc:
  dataset: anet
  debug: false
  exp_prefix: anet/ag/AGVMR
  method_type: ag
  num_workers: 4
  print_every: 100
  result_dir: results/anet/ag/AGVMR
  tensorboard_dir: tensorboard/anet/ag/AGVMR
  vis_every: 1
model:
  checkpoint_path: ''
  dqa_lambda: 0.2
  dqa_weight: 1.0
  glove_path: ''
  grounding_att_cand_dim: 512
  grounding_att_drop_prob: 0.0
  grounding_att_hdim: 256
  grounding_att_key_dim: 512
  grounding_hdim: 512
  grounding_idim: 512
  lgi_fusion_method: mul
  lgi_global_nl_drop_prob: 0.0
  lgi_global_nl_idim: 512
  lgi_global_nl_nheads: 1
  lgi_global_nl_odim: 512
  lgi_global_nl_use_bias: true
  lgi_global_nl_use_local_mask: false
  lgi_global_num_nl_block: 1
  lgi_global_satt_att_cand_dim: 512
  lgi_global_satt_att_edim: 512
  lgi_global_satt_att_hdim: 256
  lgi_global_satt_att_n: 1
  lgi_global_satt_att_use_embedding: true
  lgi_global_type: nl
  lgi_hp_hdim: 512
  lgi_hp_idim_1: 512
  lgi_hp_idim_2: 512
  lgi_local_do_downsample: false
  lgi_local_num_res_blocks: 1
  lgi_local_res_block_1d_hdim: 256
  lgi_local_res_block_1d_idim: 512
  lgi_local_res_block_1d_ksize: 15
  lgi_local_res_block_1d_odim: 512
  lgi_local_type: res_block
  loc_word_emb_vocab_size: 11125
  model_type: AGVMR
  num_semantic_entity: 5
  query_enc_emb_idim: 11125
  query_enc_emb_odim: 300
  query_enc_rnn_bidirectional: true
  query_enc_rnn_dropout: 0.5
  query_enc_rnn_hdim: 256
  query_enc_rnn_idim: 300
  query_enc_rnn_nlayer: 2
  query_enc_rnn_type: LSTM
  resume: false
  sqan_att_cand_dim: 512
  sqan_att_drop_prob: 0.0
  sqan_att_hdim: 256
  sqan_att_key_dim: 512
  sqan_qdim: 512
  tag_weight: 1.0
  use_distinct_query_attention_loss: true
  use_gpu: true
  use_temporal_attention_guidance_loss: true
  use_video_encoder: false
  video_enc_pemb_idim: 128
  video_enc_pemb_odim: 512
  video_enc_use_position: true
  video_enc_vemb_idim: 500
  video_enc_vemb_odim: 512
optimize:
  decay_factor: 0.5
  decay_step: -1
  init_lr: 0.0004
  num_step: 500
  optimizer_type: Adam
  scheduler_type: ''
test_loader:
  annotation_path:
  - data/ActivityNet/captions/annotations/val_1.json
  - data/ActivityNet/captions/annotations/val_2.json
  batch_size: 100
  data_dir: data/ActivityNet
  dataset: anet
  feature_type: C3D
  in_memory: true
  max_length: 25
  num_segment: 128
  split: val
  video_feature_path: data/ActivityNet/feats/sub_activitynet_v1-3.c3d.hdf5
  word_frequency_threshold: 1
train_loader:
  annotation_path: data/ActivityNet/captions/annotations/train.json
  batch_size: 100
  data_dir: data/ActivityNet
  dataset: anet
  feature_type: C3D
  in_memory: true
  max_length: 25
  num_segment: 128
  split: train
  video_feature_path: data/ActivityNet/feats/sub_activitynet_v1-3.c3d.hdf5
  word_frequency_threshold: 1
